### ISSUE TITLE
全新安装使用php8.2,最新版本1.2.1,主题版本2.5,打开debug模式,查看安装成功后的第一篇文章报错如下

### ISSUE THREAD

**Issue by SmartElec** [changbin1997/MWordStar#28]
全新安装使用php8.2,最新版本1.2.1,主题版本2.5,打开debug模式,查看安装成功后的第一篇文章报错如下
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'views' in 'field list'
Typecho\Db\Adapter\SQLException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'views' in 'field list' in /app/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /app/var/Typecho/Db.php(394): Typecho\Db\Adapter\Pdo->query('SELECT `views` ...', Object(PDO), 1, 'SELECT', 'typecho_content...')
#1 /app/var/Typecho/Db.php(442): Typecho\Db->query(Object(Typecho\Db\Query))
#2 /app/usr/themes/MWordStar/functions.php(344): Typecho\Db->fetchRow(Object(Typecho\Db\Query))
#3 /app/usr/themes/MWordStar/post.php(57): postViews(Object(Widget\Archive))
#4 /app/var/Widget/Archive.php(1345): require_once('/app/usr/themes...')
#5 /app/var/Typecho/Router.php(88): Widget\Archive->render()
#6 /app/index.php(23): Typecho\Router::dispatch()
```
更换默认主题报错消失

**Comment by changbin1997** [comment]
你可以把主题版本换成最新的 2.6 试一下

**Comment by SmartElec** [comment]
> 你可以把主题版本换成最新的 2.6 试一下

有点曲折,typecho自动升级成1.3.0了,换成默认主题再换回来,暂时没报错.  文章归档与友情链接都显示Not Found了.

**Comment by changbin1997** [comment]
如果你说的是文章归档和友情链接页面的话，可以删除这两个独立页面，重新创建，然后选择对应的页面模板。
